### ISSUE TITLE
Files are being downloaded correctly, but not patched

### ISSUE THREAD

**Issue by Ven0m0** [XDream8/revanced-creator#1]
I am using the ubuntu wsl and i get this error.
`jannik@Jannik_PC:~$ cd /mnt/c/
jannik@Jannik_PC:/mnt/c$ cd users
jannik@Jannik_PC:/mnt/c/users$ cd janni/
jannik@Jannik_PC:/mnt/c/users/janni$ cd downloads
jannik@Jannik_PC:/mnt/c/users/janni/downloads$ mkdir -p revanced
jannik@Jannik_PC:/mnt/c/users/janni/downloads$ cd revanced
jannik@Jannik_PC:/mnt/c/users/janni/downloads/revanced$ sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3294  100  3294    0     0  15836      0 --:--:-- --:--:-- --:--:-- 15760
removing olds
Downloading revanced-cli, revanced-patches and revanced-integrations
1) downloading https://github.com/revanced/revanced-cli/releases/download/v2.5.3/revanced-cli-2.5.3-all.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 43.2M  100 43.2M    0     0  31.5M      0  0:00:01  0:00:01 --:--:-- 43.0M
2) downloading https://github.com/revanced/revanced-patches/releases/download/v2.13.3/revanced-patches-2.13.3.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  340k  100  340k    0     0   796k      0 --:--:-- --:--:-- --:--:--  796k
3) downloading https://github.com/revanced/revanced-integrations/releases/download/v0.24.0/app-release-unsigned.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  696k  100  696k    0     0  1939k      0 --:--:-- --:--:-- --:--:-- 1939k
4) downloading https://github.com/XDream8/revanced-creator/releases/download/v0.1/YouTube-17.26.35.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  131M  100  131M    0     0  26.4M      0  0:00:04  0:00:04 --:--:-- 28.1M
patching process started(non-root)
it may take a while please be patient
sh: 60: java: not found`

The error might occurr because i am using WSL 1 instead of WSL 2.

**Comment by XDream8** [comment]
You probably dont have java17 installed

**Comment by XDream8** [comment]
i will add checks for whether java is installed or not

**Comment by XDream8** [comment]
Can you install `openjdk-17-jdk` and `openjdk-17-jre` packages then try again

**Comment by Ven0m0** [comment]
it was indeed java. I installed java 17, but only through windows, not in WSL. Works as intended now.

**Comment by XDream8** [comment]
good to hear that :)
