### ISSUE TITLE
Option for using self provided apk

### ISSUE THREAD

**Issue by xiangyann** [XDream8/revanced-creator#10]
The YouTube patches in revanced upstream are currently a few subversions ahead of what the base is currently offered in this repository.

To be able to use the newest version while using this script, currently my method is to fork the repo and omit the $apk_link and just placing the desired version I got from "a place", which isn't quite elegant to be honest.

I think this is a good opportunity to implement a param for user defined apk file location that will ignore the version header(and avoid grabbing from GitHub) if exists.

**Comment by XDream8** [comment]
I will add an option for it to what_to_patch arg soon

**Comment by XDream8** [comment]
it is added, check out readme
