### ISSUE TITLE
Dont download integrations when not needed, dont multi-download same file

### ISSUE THREAD

**Issue by TheJeterLP** [XDream8/revanced-creator#14]
Currently the integrations are still being downloaded even on app when they're not being used. See log:
`3) downloading https://github.com/revanced/revanced-integrations/releases/download/v0.33.1/app-release-unsigned.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 37  639k   37  239k    0     0   701k      0 --:--:-- --:--:-- --:--:--  701k
100  639k  100  639k    0     0  1785k      0 --:--:-- --:--:-- --:--:-- 25.9M
curl: Saved to filename 'app-release-unsigned.apk'`

Also the revanced-patches file is being downloaded over and over again for every app to be patched. The CLI, patches and integrations should only be downloaded ONCE the actions runs and then just use those files for every app. Will make the action run way faster.

**Comment by XDream8** [comment]
fixed, thanks for your reports!

**Comment by TheJeterLP** [comment]
> fixed, thanks for your reports!

No problem :)
