### ISSUE TITLE
Releases: transfer old versions to separate release tag

### ISSUE THREAD

**Issue by n-ce** [XDream8/revanced-creator#16]
the way the release list is maintained right now it would soon be a very long list
itd be wise to only have the latest versions of each app on the release version a(say)
and older versions on release version b(say)

**Comment by XDream8** [comment]
i think having seperate releases for all apps would be better

Like:
1. Youtube Apk's
2. Youtube Music Apk's
3. Reddit Apk's
4. Keystores

**Comment by XDream8** [comment]
switched to seperate releases for all apps
