### ISSUE TITLE
Broken YT Building with Root

### ISSUE THREAD

**Issue by bassmadrigal** [XDream8/revanced-creator#21]
It seems  5c8c319 broke building a root enabled YouTube Revanced by commenting out the checkadb function call ([patch.sh#L80](https://github.com/XDream8/revanced-creator/blob/c5c09c83580b73f18eb92c38cf002c36b4427f97/patch.sh#L180)) within the checking root section in your main function. This prevents the script from getting the device ID from adb and then causes the patch function to fail since the -d is not getting $deviceid passed to it. Instead, it's using the next argument as the $deviceid, which causes the following output with the bottom line being the error (followed by the help for revanced-cli, but I left it out for ease of viewing):

```
patching process started(root)
it may take a while please be patient
Expected parameter for option '--deploy-on' but found '-e'
```

The fix was as easy as uncommenting that line, but I'm not sure if it was just missed when you did the cleanup or if there was another reason it was commented out. If desired, I could submit a pull request for the fix.

Thanks for the awesome script!

**Comment by XDream8** [comment]
sorry my bad, after cleanup i had to disable adb checks to test if root=1 adds required args to create root apk
since i don't have a rooted device
