### ISSUE TITLE
Tiktok not opening

### ISSUE THREAD

**Issue by hubono** [XDream8/revanced-creator#23]
Hello
Using a one plus 7 pro and was trying the tiktok apk.
It installs but after installation it doesn't open.
I tap on the icon but nothing happens.

**Comment by H3rmit** [comment]
> Hello Using a one plus 7 pro and was trying the tiktok apk. It installs but after installation it doesn't open. I tap on the icon but nothing happens.

Same problem.

**Comment by hubono** [comment]
Hi
I figured it out. Im using a tracker blocker and i blocked all the trackers in the tiktok app that's why it doesn't open for me. Once unblocked the trackers, it worked.
