### ISSUE TITLE
Can't update - conflicting app signatures

### ISSUE THREAD

**Issue by viperML** [XDream8/revanced-creator#30]
I believe this is a known issue, but i want to raise attention to it.

Currently I can't update the revanced-patched apps with the same apps from this repo, as android complains of "Conflicting app signatures"

**Comment by XDream8** [comment]
I will update gh action builds to add the support for keystores back.

But this time I will not share the keystore files. What I am gonna do is storing base64 encoded output of keystore file in action secrets and decoding it in a action.

**Comment by viperML** [comment]
I don't have much experience with android signing, but can't you just pull the decrypted keys from the repo secrets in the action?

Of course, it would be crucial to make sure the key doesn't leak in the action logs or artifacts

**Comment by XDream8** [comment]
> I don't have much experience with android signing, but can't you just pull the decrypted keys from the repo secrets in the action?

I don't think thats possible. In repo secrets you can only store string type secrets so i think only way is using base64.

**Comment by XDream8** [comment]
I got wrong version of the keystore errors, is it possible that we need integrations to create a apk with custom keystore.

I will test this theory

**Comment by XDream8** [comment]
I couldn't find a solution, I will open a issue in [revanced-cli](https://github.com/revanced/revanced-cli)

**Comment by XDream8** [comment]
I used a keystore file created by revanced-cli for now. Because it seems that version 3 key stores are not supported by revanced-cli and I could not find a way to create version 2 key stores.

**Comment by viperML** [comment]
Should we close this issue as completed?

On a side note - now that updating works - I will look into creating some "custom repo" for F-Droid or Aurora Droid, so users can receive updates automatically

**Comment by XDream8** [comment]
An F-Droid repo would be really nice.

Closing this issue!
