### ISSUE TITLE
Better source to fetch youtube apk? 

### ISSUE THREAD

**Issue by Tec43** [XDream8/revanced-creator#7]
Hey! so as you may already know that i am working on a script to build vanced on Google Collab. So in the process, i analysed the .sh file and found that it gets the youtube or the youtube music apk from the releases of the repository. The problem is that only 2 versions of youtube and 1 version of youtube music is released and most probably some time in the future you may stop upload latest apk files. 

Would it possible to edit the script so that it fetches the apk file from a more reliable source like **APKmirror** or Apkpure?

**Comment by XDream8** [comment]
I first tried that but since apkmirror and apkpure both have protection i couldnt do it with a shell script

**Comment by Tec43** [comment]
Oh, that's not good. Anyway I will be looking for better sources without protection, till then
