### ISSUE TITLE
Automatize actions builds

### ISSUE THREAD

**Issue by giuseppe998e** [XDream8/revanced-creator#9]
I was thinking that you could automate actions builds whenever a new version is released in the `revanced-patches`(or/and others) repo, using **IFTTT** (https://ifttt.com/github/triggers/any_new_release) and **GitHub** webhooks.

**Comment by XDream8** [comment]
instead of that i can make CI run once everyday with cron

**Comment by giuseppe998e** [comment]
From my point of view I would rather see a new build having the confidence of an actual patches update, instead of seeing a new build every day having to go and check on the other repo whether or not it is the same as the one from the day before

**Comment by XDream8** [comment]
I tried IFTTT but it does not let me run a github-action.

**Comment by XDream8** [comment]
it may be possible [with this](https://github.com/marketplace/run-actions-from-comment)

**Comment by XDream8** [comment]
I tested it and it does not work

**Comment by giuseppe998e** [comment]
You should try using this [method](https://mainawycliffe.dev/blog/github-actions-trigger-via-webhooks/)

**Comment by XDream8** [comment]
[found this](https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release), I will try that later

**Comment by XDream8** [comment]
done, we will see if this works

Created a workflow to check new releases, this runs everyday at 10 am. If there is a new release this workflow updates release-versions/patches-latest.md

Then I updated CI workflow to run on commits to release-versions/patches-latest.md

**Comment by XDream8** [comment]
it seems to be working

**Comment by TheJeterLP** [comment]
> Created a workflow to check new releases, this runs everyday at 10 am. 

Currently it runs every hour, could you change that? It runs so often that it's hard to find the real action

**Comment by XDream8** [comment]
How about we run it once for every 6 hour?

**Comment by TheJeterLP** [comment]
> How about we run it once for every 6 hour or every 12 hour?

Sounds good

**Comment by rollingmoai** [comment]
@XDream8 how about automating releases in https://github.com/XDream8/revanced-creator/releases for each new build?
